# Programming for Data Analysis Assignment 2019

- Ref:
- Location: C:\Users\35386\Desktop\Prog-DA-Assignment

# Part 1. Overall Purpose of the Package.
- Ref: https://jupyter.org/
- 'Project Jupyter exists to develop open-source software, open-standards, and services for interactive computing across dozens of programming languages.'
- It's default entry mode is 'code', and at its very basic, this will run programs like any other integrated Development Environment, such as the ipython interpereter. Its main advantage however, as outlined above, is that it interacts with other programming langugaes and it is very useful for investigating Datasets. 
- It has 3 main types of cells. The Mark down cell which we are currently in displays trxt as HTML.
- The second is the Code cell, that accepts code, the following is an example of this:

In [1]:
a = 100
b = 50
print (b-a)

-50


- The cell above, is an output cell, that gives the output of the code cell. Double clicking on this will hide it.
- There are a number of other keyboard shortcuts available in the help menu. 

# Advantages
- Ref: https://www.analyticsvidhya.com/blog/2018/05/starters-guide-jupyter-notebook/

- Jupyter Notebook is an open-source web application that allows us to create and share codes and documents.

- It provides an environment, where you can document your code, run it, look at the outcome, visualize data and see the results without leaving the environment. This makes it a handy tool for performing end to end data science workflows – data cleaning, statistical modeling, building and training machine learning models, visualizing data, and many, many other uses.

- Jupyter Notebooks really shine when you are still in the prototyping phase. This is because your code is written in indepedent cells, which are executed individually. This allows the user to test a specific block of code in a project without having to execute the code from the start of the script. Many other IDE enviornments (like RStudio) also do this in several ways, but I have personally found Jupyter’s individual cells structure to be the best of the lot. 
- Jupyter Notebooks are incredibly flexible, interactive and powerful tools in the hands of a data scientist. They even allow you to run other languages besides Python, like R, SQL, etc. Since they are more interactive than an IDE platform, they are widely used to display codes in a more pedagogical manner.
- 

# Disadvantages
- Ref: https://towardsdatascience.com/5-reasons-why-jupyter-notebooks-suck-4dc201e27086
- 1. It is almost impossible to enable good code versioning
- Do you work in a data team that collaborates and might work on the same notebooks? Probably you then tried to merge two jupyter notebooks. Due to the fact that jupyter notebooks are stored as big JSON files merging two notebooks is virtually impossible. This is bad because we cannot apply tools for software teams like a good git workflow will pull requests and reviews.
- 2. There is no IDE integration, no linting, no code-style correction
- Once I posted a snippet from a jupyter notebook into slack python developer group. I cannot say how ashamed I felt about the way they blamed me for not following pep conventions. Jupyter has no kind of linting meaning you can write very badly styled coded. Just try to copy your code into your favorable code editor with linting, and you will see what I mean. Data Scientist are not software engineers and therefore tools that govern their code quality and help to improve it are very important.
- 3. Very hard to test
- A colleague of mine once said when you work with jupyter notebooks you basically forget software engineering. And he is right! It is so damn hard to structure your code reasonable, put your code into functions and then develop tests for them. I’m a huge fan of test-driven development and I can only recommend moving away as quickly as possible from jupyter notebooks when you develop serious data pipelines. Jupyter notebooks are a tool for exploration not for production, as soon as you want to reproduce some experiments and run notebooks frequently. Dump your jupyter notebooks and develop your python script based on test-driven-development principles. (And yes you can also develop data products using TDD, you just need to get your fixtures right!)
- 4. The non-linear workflow of jupyter
- Did you ever destroy your current working state when jumping between cells of jupyter notebooks? Yes? I can tell you’re not alone this happens to me quite frequently. This way of jumping around between cells can result in unreproducible experiments. The interactive way of coding and jumping in a notebook between cells is both one of jupyter notebooks best features and its biggest weakness.
- 5. Jupyter is bad for running long asynchronous tasks
- I like to say big data means big problems. Usually, you start when approaching a problem with a small dataset that fits into your memory. You will come to the point where your machine is not good enough anymore. You could then jump to tools like spark, dask and distributed and run them from your notebook. I suggest not to do so. If you got your first data exploration done and want to rum large-scale experiments or even finalize your data pipeline. Pull your code out of the jupyter notebook start a proper python project, create fixtures, write tests and deploy your application then to a cluster. This will help you a lot to build reliable data-driven products.

# Simple Random Data function

- Ref: https://www.investopedia.com/terms/s/simple-random-sample.asp
- "A simple random sample is a subset of a statistical population in which each member of the subset has an equal probability of being chosen. A simple random sample is meant to be an unbiased representation of a group". In numpy, the Random sampling provides ten data functions from which random numbers can be drawn. Each of the data functions has specific peramiters that will impact the range from which the random sample (or subset can be drawn. 
- Simple Randon Data is a subpackage of numpy and is therefore can be imported into juypter notebook. 
- Ref: 

# Permutations Function
- Ref: https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.permutation.html
- The permutation function in numpy is called by giving the command numpy.random.permutation(x) or numpy.random.shuffle (x).
- In numpy.random.permutation(x) gives as an output a randomly permutation of a sequence or a permutation of a range. 
- In numpy.random.shuffle(x) the sequence is modified by shuffling its content in palce.

Ref: https://github.com/numpy/numpy/issues/8250

In [2]:
import numpy as np

N = 10
A = np.random.permutation([2, 3, 5, 7, 11])
B = np.random.permutation (N)
c = np.arange(12).reshape(3,4)
D = np.arange(12).reshape(4,3)

In [3]:
print (A)

[ 5  7  2 11  3]


In [4]:
print (B)

[0 3 4 2 7 8 5 6 1 9]


In [5]:
print (c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print (c.shape)

(3, 4)


In [7]:
print ((np.random.permutation(c)))
(np.random.permutation(c))
c

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
print (D)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
print (D.shape)

(4, 3)


In [10]:
print (np.random.shuffle(D))
np.random.shuffle(D)
D

None


array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5]])

- One of the difference noted here is how each function is called, in shuffle using print outputs None. 

# Distribution Functions